### ISSUE TITLE
使用Gemini API报错

### ISSUE THREAD

**Issue by Paladin-F** [whyiyhw/chatgpt-wechat#102]
国外主机，使用openai 的key可以正常使用，切换成Gemini就不行了，#help可以正常弹提示，但是发送对话信息则会导致go的报错，信息如下：
```
Starting server at 0.0.0.0:8888...
incoming message: RxMessage { FromUserID: "AAAAAAA", SendTime: 1704988397000000000, MsgType: "text", MsgID: 7322869406999813673, AgentID: 1000003, Event: "", ChangeType: "", Content: "测试" }
上下文请求信息： collection.Prompt
[{user {text/plain 测试}}]
{"@timestamp":"2024-01-11T23:53:19.280+08:00","caller":"response/response.go:63","content":"","level":"info","response":{"code":200,"msg":"成功","data":{"message":"ok"}},"span":"07a8e483cc753d36","trace":"38cf60ab646e7d3ba929ff001773501a"}
{"@timestamp":"2024-01-11T23:53:19.281+08:00","caller":"accesslog/accesslog.go:29","content":"","level":"info","request":{"url":"/api/msg/push","method":"POST","query":"","body":"{\"channel\":\"gemini\",\"msg\":\"测试\",\"user_id\":\"AAAAAAA\",\"agent_id\":1000003}","header":{"Accept-Encoding":["gzip"],"Authorization":["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzA5MDgzOTAsImlhdCI6MTcwNDk4ODM5MCwidXNlcklkIjoxfQ.ohjY1GHfuQWgWkxJSwseMmdctSKlQzw6B1vSQ52lEW4"],"Content-Length":["74"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]},"const":6},"span":"07a8e483cc753d36","trace":"38cf60ab646e7d3ba929ff001773501a"}
{"@timestamp":"2024-01-11T23:53:19.281+08:00","caller":"handler/loghandler.go:147","content":"[HTTP] 200 - POST /api/msg/push - [::1]:35204 - Go-http-client/1.1","duration":"7.4ms","level":"info","span":"07a8e483cc753d36","trace":"38cf60ab646e7d3ba929ff001773501a"}
start: 0
start: 0
body{"contents":[{"parts":[{"text":"测试"}],"role":"user"}]}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x275548]

goroutine 65 [running]:
net/http.(*Client).deadline(0x0?)
        /usr/local/go/src/net/http/client.go:194 +0x18
net/http.(*Client).do(0x0, 0x40001ac800)
        /usr/local/go/src/net/http/client.go:608 +0x198
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:590
chat/common/gemini.(*ChatClient).ChatStream(0x4000657780, {0x400070c4e0, 0x1, 0x1}, 0x0?)
        /build/common/gemini/chat.go:205 +0xeb8
chat/service/chat/api/internal/logic.(*ChatLogic).Chat.func1.1()
        /build/service/chat/api/internal/logic/chatlogic.go:92 +0x58
created by chat/service/chat/api/internal/logic.(*ChatLogic).Chat.func1 in goroutine 53
        /build/service/chat/api/internal/logic/chatlogic.go:91 +0x138
```

**Comment by whyiyhw** [comment]
先清理 对话上下文 ，#clear 再重新对话就好，目前在在调整数据结构适配文本与图像

**Comment by Paladin-F** [comment]
已经尝试#clear，之后还是同样的问题
```
Defaulted container "chat-api" out of: chat-api, chat-websocket, redis, pgvector
Starting server at 0.0.0.0:8888...
incoming message: RxMessage { FromUserID: "AAAAAAA", SendTime: 1705035262000000000, MsgType: "text", MsgID: 7323070690008408617, AgentID: 1000003, Event: "", ChangeType: "", Content: "#clear" }
{"@timestamp":"2024-01-12T12:54:23.726+08:00","caller":"response/response.go:63","content":"","level":"info","response":{"code":200,"msg":"成功","data":{"message":"ok"}},"span":"60ceaa1cd3a0e8a7","trace":"8bf46bf74711053983023cc7c6dc75d0"}
{"@timestamp":"2024-01-12T12:54:23.727+08:00","caller":"accesslog/accesslog.go:29","content":"","level":"info","request":{"url":"/api/msg/push","method":"POST","query":"","body":"{\"channel\":\"gemini\",\"msg\":\"#clear\",\"user_id\":\"AAAAAAA\",\"agent_id\":1000003}","header":{"Accept-Encoding":["gzip"],"Authorization":["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzA5NTUwNzIsImlhdCI6MTcwNTAzNTA3MiwidXNlcklkIjoxfQ.nntScyKldf6jt31rBLX6g1VQ5qUMFsl31cyMmub-h3Y"],"Content-Length":["74"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]},"const":6},"span":"60ceaa1cd3a0e8a7","trace":"8bf46bf74711053983023cc7c6dc75d0"}
{"@timestamp":"2024-01-12T12:54:23.728+08:00","caller":"handler/loghandler.go:147","content":"[HTTP] 200 - POST /api/msg/push - [::1]:56856 - Go-http-client/1.1","duration":"8.3ms","level":"info","span":"60ceaa1cd3a0e8a7","trace":"8bf46bf74711053983023cc7c6dc75d0"}
incoming message: RxMessage { FromUserID: "AAAAAAA", SendTime: 1705035286000000000, MsgType: "text", MsgID: 7323070795505257257, AgentID: 1000003, Event: "", ChangeType: "", Content: "测试测试" }
上下文请求信息： collection.Prompt
[{user {text/plain 测试测试}}]
{"@timestamp":"2024-01-12T12:54:48.368+08:00","caller":"response/response.go:63","content":"","level":"info","response":{"code":200,"msg":"成功","data":{"message":"ok"}},"span":"7f0c80bb9c89b406","trace":"8a8072935254e5ebb1a438932de4a2de"}
{"@timestamp":"2024-01-12T12:54:48.369+08:00","caller":"accesslog/accesslog.go:29","content":"","level":"info","request":{"url":"/api/msg/push","method":"POST","query":"","body":"{\"channel\":\"gemini\",\"msg\":\"测试测试\",\"user_id\":\"AAAAAAA\",\"agent_id\":1000003}","header":{"Accept-Encoding":["gzip"],"Authorization":["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzA5NTUwNzIsImlhdCI6MTcwNTAzNTA3MiwidXNlcklkIjoxfQ.nntScyKldf6jt31rBLX6g1VQ5qUMFsl31cyMmub-h3Y"],"Content-Length":["80"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]},"const":2},"span":"7f0c80bb9c89b406","trace":"8a8072935254e5ebb1a438932de4a2de"}
{"@timestamp":"2024-01-12T12:54:48.369+08:00","caller":"handler/loghandler.go:147","content":"[HTTP] 200 - POST /api/msg/push - [::1]:58626 - Go-http-client/1.1","duration":"3.7ms","level":"info","span":"7f0c80bb9c89b406","trace":"8a8072935254e5ebb1a438932de4a2de"}
body{"contents":[{"parts":[{"text":"测试测试"}],"role":"user"}]}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x275548]

goroutine 77 [running]:
net/http.(*Client).deadline(0x0?)
        /usr/local/go/src/net/http/client.go:194 +0x18
net/http.(*Client).do(0x0, 0x4000782000)
        /usr/local/go/src/net/http/client.go:608 +0x198
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:590
chat/common/gemini.(*ChatClient).Chat(0x400090a180, {0x400043a960, 0x1, 0x1})
        /build/common/gemini/chat.go:77 +0x96c
chat/service/chat/api/internal/logic.(*ChatLogic).Chat.func1()
        /build/service/chat/api/internal/logic/chatlogic.go:143 +0x158
created by chat/service/chat/api/internal/logic.(*ChatLogic).Chat in goroutine 32
        /build/service/chat/api/internal/logic/chatlogic.go:86 +0x680
root@kr1:/cluster/nfs/chatapi/api# 
```
