### ISSUE TITLE
需要checkout到哪个版本才能运行呢？

### ISSUE THREAD

**Issue by Boxer-egg** [whyiyhw/chatgpt-wechat#117]
之前闲着没事更新过一次，git checkout a7f5427 后重新build又好用了。但是这台机器网络不行了，需要换一台。

我换了一台后，无论我checkout到那个提交上，每次build完，up之后，chat-web一直在重启。

求助一下

**Comment by Boxer-egg** [comment]
```
 docker logs  chat-api

2024/11/08 16:43:05 /build/service/chat/api/internal/svc/servicecontext.go:35
[error] failed to initialize database, got error failed to connect to `user=chat database=chat`: 172.21.0.3:5432 (pgvector): dial error: dial tcp 172.21.0.3:5432: connect: connection refused
panic: failed to connect to `user=chat database=chat`: 172.21.0.3:5432 (pgvector): dial error: dial tcp 172.21.0.3:5432: connect: connection refused

goroutine 1 [running]:
chat/service/chat/api/internal/svc.NewServiceContext({{{{0xc00011ece0, 0x8}, {{...}, {...}, {...}, {...}, {...}, {...}, 0x0, 0x0, ...}, ...}, ...}, ...})
	/build/service/chat/api/internal/svc/servicecontext.go:45 +0x3f6
main.main()
	/build/service/chat/api/chat.go:49 +0x30b
Starting server at 0.0.0.0:8888...
```

**Comment by Boxer-egg** [comment]
重新拉了一次，好了。。
之前好像是少了key
