### ISSUE TITLE
在执行调用注册api的时候报错

### ISSUE THREAD

**Issue by deemoartisan** [whyiyhw/chatgpt-wechat#36]
curl: (7) Failed to connect to localhost port 8888: Connection refused

用的云函数那条路子，查了一下也没占用8888，chat-web-1容器无法启动，日志显示
Starting server at 0.0.0.0:8887...
{"@timestamp":"2023-04-13T03:52:00.347+08:00","caller":"rest/server.go:304","content":"listen tcp 0.0.0.0:8887: bind: address already in use","level":"error"}
panic: listen tcp 0.0.0.0:8887: bind: address already in use

goroutine 1 [running]:
github.com/zeromicro/go-zero/rest.handleError(...)
	/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/server.go:305
github.com/zeromicro/go-zero/rest.(*Server).Start(0x11969c0?)
	/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/server.go:116 +0xb3
main.main()
	/build/service/chat/api/chat.go:76 +0x5a5

求教。。。

**Comment by deemoartisan** [comment]
后续：在配置文件里和云函数里面都把端口改了，注册成功了。但是现在问题是给应用发消息，得不到回复。。

**Comment by deemoartisan** [comment]
可信ip已经配置为服务器公网ip，chat-web-1日志如下：
Starting server at 0.0.0.0:8900...
{"@timestamp":"2023-04-13T04:13:27.857+08:00","caller":"sqlx/stmt.go:132","content":"sql query: SELECT `id`,`name`,`email`,`password`,`created_at`,`updated_at` FROM `user` WHERE email = 'deemoartisan@gmail.com'","duration":"66.1ms","level":"info","span":"ce9a4e3c9e336d59","trace":"16d0d4f731ba58b4f576c5735ecf35bd"}
{"@timestamp":"2023-04-13T04:13:28.036+08:00","caller":"sqlx/stmt.go:132","content":"sql exec: insert into `user` (`name`,`email`,`password`) values ('deemo', 'deemoartisan@gmail.com', '$2a$10$yYvpHOvhcGFZjLgTf9nBHuLTdXQxrn8ZYDjDKj9UCt/95XJhAJrHy')","duration":"16.4ms","level":"info","span":"21d85fa04f233e61","trace":"16d0d4f731ba58b4f576c5735ecf35bd"}
{"@timestamp":"2023-04-13T04:13:28.092+08:00","caller":"response/response.go:63","content":"","level":"info","response":{"code":200,"msg":"成功","data":{"message":"注册成功，去登录吧~"}},"span":"1a9caccaa8ca02b8","trace":"16d0d4f731ba58b4f576c5735ecf35bd"}
{"@timestamp":"2023-04-13T04:13:28.092+08:00","caller":"handler/loghandler.go:137","content":"[HTTP] 200 - POST /api/user/register - 172.18.0.1:43980 - curl/7.74.0 - slowcall(635.9ms)","duration":"635.9ms","level":"slow","span":"1a9caccaa8ca02b8","trace":"16d0d4f731ba58b4f576c5735ecf35bd"}
{"@timestamp":"2023-04-13T04:13:28.092+08:00","caller":"accesslog/accesslog.go:28","content":"","level":"info","request":{"url":"/api/user/register","method":"POST","query":"","body":"{\"email\": \"deemoartisan@gmail.com\",\"name\": \"deemo\",\"password\": \"deemo\"}","header":{"Accept":["*/*"],"Content-Length":["71"],"Content-Type":["application/json"],"User-Agent":["curl/7.74.0"]},"const":-364},"span":"1a9caccaa8ca02b8","trace":"16d0d4f731ba58b4f576c5735ecf35bd"}
{"@timestamp":"2023-04-13T04:13:28.093+08:00","caller":"handler/loghandler.go:160","content":"[HTTP] 200 - POST /api/user/register - 172.18.0.1:43980 - curl/7.74.0","duration":"635.9ms","level":"info","span":"1a9caccaa8ca02b8","trace":"16d0d4f731ba58b4f576c5735ecf35bd"}
{"@timestamp":"2023-04-13T04:14:39.802+08:00","caller":"sqlx/stmt.go:132","content":"sql query: SELECT `id`,`name`,`email`,`password`,`created_at`,`updated_at` FROM `user` WHERE email = 'deemoartisan@gmail.com'","duration":"7.8ms","level":"info","span":"93d1a68670e2e5fc","trace":"c55d06a50e19b58f22fe486896fdcd8d"}
{"@timestamp":"2023-04-13T04:14:39.945+08:00","caller":"response/response.go:63","content":"","level":"info","response":{"code":200,"msg":"成功","data":{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDcyNTA0NzksImlhdCI6MTY4MTMzMDQ3OSwidXNlcklkIjoxfQ.pUcPWnW8cETNgHLZcIpDliAGr2ILICK1j7dIIteBrWA"}},"span":"e7b4348f013d388a","trace":"c55d06a50e19b58f22fe486896fdcd8d"}
{"@timestamp":"2023-04-13T04:14:39.946+08:00","caller":"accesslog/accesslog.go:28","content":"","level":"info","request":{"url":"/api/user/login","method":"POST","query":"","body":"{\"email\": \"deemoartisan@gmail.com\",\"password\": \"deemo\"}","header":{"Accept":["*/*"],"Content-Length":["55"],"Content-Type":["application/json"],"User-Agent":["curl/7.74.0"]},"const":151},"span":"e7b4348f013d388a","trace":"c55d06a50e19b58f22fe486896fdcd8d"}
{"@timestamp":"2023-04-13T04:14:39.946+08:00","caller":"handler/loghandler.go:160","content":"[HTTP] 200 - POST /api/user/login - 172.18.0.1:60100 - curl/7.74.0","duration":"151.4ms","level":"info","span":"e7b4348f013d388a","trace":"c55d06a50e19b58f22fe486896fdcd8d"}

**Comment by deemoartisan** [comment]
破案了，是云函数那里的req_host配置里面多了个英文句号。。
